from typing import Protocol


class ElementReader(Protocol):
    def text(self, selector: str) -> str | None: ...
    def attribute(self, selector: str, name: str) -> str | None: ...


class PageReader(ElementReader, Protocol):
    @property
    def url(self) -> str: ...
    @property
    def title(self) -> str: ...
    def exists(self, selector: str) -> bool: ...
    def value(self, selector: str) -> str | None: ...
    def elements(self, selector: str) -> list[ElementReader]: ...
