const labels: Record<string, string> = {
  RUNNING: '运行中', PAUSED: '已暂停', STOPPED: '已停止', STALE: '心跳过期',
  USER_PAUSED: '人工暂停', MESSAGE_DISCOVERY_UNAVAILABLE: '消息页面不可用',
  JOB_DISCOVERY_UNAVAILABLE: '职位页面不可用',
  RECOMMENDATION_DISCOVERY_UNAVAILABLE: '推荐页面不可用',
  RESULT_NOT_OBSERVED: '发送结果待核对',
  JOB_SOURCE_URL_MISSING: '未保存原职位链接',
  JOB_SOURCE_URL_UNAVAILABLE: '原职位链接暂不可用',
  SESSION_READY: '页面就绪', SESSION_UNAVAILABLE: '页面不可用',
  OPEN: '暂停（模型不可用）', PROBING: '正在检测', CLOSED: '正常可用',
  CONFIGURED: '已配置', UNCONFIGURED: '未配置',
  GREETING: '主动招呼', REPLY: '普通回复', RESUME: '发送默认简历',
  MISMATCH_DECLINE: '礼貌拒绝', SUCCEEDED: '已成功', APPROVED: '待执行',
  FAILED_RETRYABLE: '可重试失败', FAILED_FINAL: '最终失败',
  OUTCOME_UNKNOWN: '结果待核对', ELIGIBLE: '符合策略条件',
  MISMATCH: '不匹配', ROUGH_MATCH: '初步匹配', FULL_MATCH: '完全匹配',
  UNKNOWN: '信息不足',
  CONTACT: '建议沟通', SKIP: '不建议沟通', REVIEW: '需要进一步判断',
  FILTERED_OUT: '硬性排除',
  CONVERSATION_ACTIVE: '已有会话', GREETING_SENT_PENDING_SYNC: '已打招呼，等待消息同步',
  GREETING_RETRY_PENDING: '发送失败，等待重试', GREETING_OUTCOME_UNKNOWN: '发送结果待确认',
  GREETING_IN_PROGRESS: '正在发起沟通', GREETING_FAILED: '发送失败',
  READY_TO_CONTACT: '满足条件，尚未发起', NOT_CONTACTED: '未发起沟通',
  APPROVED_TARGET_PAGE_NOT_FOUND: '发送时没有找到对应职位页',
  APPROVED_TARGET_PAGE_AMBIGUOUS: '检测到多个相同职位页',
  SUPPORTED_PAGE_ROOT_NOT_FOUND: '职位页面结构发生变化',
  GREETING_ALREADY_EXISTS: '已有招呼动作', AUTO_GREET_DISABLED: '主动沟通开关未开启',
  STRATEGY_NOT_BOUND: '尚未绑定求职策略',
  PROHIBITED_OR_FRAUD_DIRECTION: '岗位疑似违规、欺诈或明确不接受',
  COMPANY_BLACKLISTED: '公司在黑名单中', INDUSTRY_EXCLUDED: '行业属于排除范围',
  WORK_MODE_CONFLICT: '工作模式不符合要求', LOCATION_CONFLICT: '工作地点不符合要求',
  WORK_MODE_UNKNOWN: '办公方式尚未明确',
  SALARY_CONFLICT: '薪资低于要求', JOB_DIRECTION_CONFLICT: '岗位方向不符合求职方向',
  JOB_DIRECTION_UNKNOWN: '岗位方向信息不足',
  FULL_JOB_CONTEXT_AVAILABLE: '岗位信息充分且符合策略',
  RELATED_DIRECTION_WITHOUT_CONFLICT: '岗位方向相关，暂未发现明确冲突',
  RESUME_SEND_DENIED: '简历发送条件未满足',
  INBOUND_RESUME_REQUEST_ALLOWED: '对方索要简历，可以自动发送',
  QUALIFICATION_MISMATCH: '岗位已判定不匹配',
  ALLOW_AUTO: '允许自动执行', REQUIRE_CONFIRMATION: '等待人工确认', DENY: '不会执行',
  RULE_TEMPLATE: '规则回复', KNOWLEDGE_BASE: '知识库回复', LLM: 'AI生成', HUMAN: '人工处理',
  PENDING: '等待执行', ACTIVE: '处理中', FAILED: '发送失败', DENIED: '不会发送',
}

export const businessLabel = (code?: string) => {
  if (!code) return '-'
  return labels[code] ?? `未知状态（${code}）`
}
