const labels: Record<string, string> = {
  RUNNING: '运行中', PAUSED: '已暂停', STOPPED: '已停止', STALE: '心跳过期',
  USER_PAUSED: '人工暂停', MESSAGE_DISCOVERY_UNAVAILABLE: '消息页面不可用',
  JOB_DISCOVERY_UNAVAILABLE: '职位页面不可用',
  RECOMMENDATION_DISCOVERY_UNAVAILABLE: '推荐页面不可用',
  RESULT_NOT_OBSERVED: '发送结果待核对',
  JOB_SOURCE_URL_MISSING: '未保存原职位链接',
  JOB_SOURCE_URL_UNAVAILABLE: '原职位链接暂不可用',
  JOB_PAGE_NOT_READY: '职位页面尚未加载完成', LOGIN_REQUIRED: '平台登录状态失效',
  VERIFICATION_REQUIRED: '平台需要人工验证',
  SESSION_READY: '页面就绪', SESSION_UNAVAILABLE: '页面不可用',
  OPEN: '暂停（模型不可用）', PROBING: '正在检测', CLOSED: '正常可用',
  CONFIGURED: '已配置', UNCONFIGURED: '未配置',
  GREETING: '主动招呼', REPLY: '普通回复', RESUME: '发送默认简历',
  MISMATCH_DECLINE: '礼貌拒绝', SUCCEEDED: '已成功', APPROVED: '待执行',
  FAILED_RETRYABLE: '可重试失败', FAILED_FINAL: '最终失败',
  OUTCOME_UNKNOWN: '结果待核对', ELIGIBLE: '符合策略条件',
  MISMATCH: '不匹配', ROUGH_MATCH: '初步匹配', FULL_MATCH: '完全匹配',
  UNKNOWN: '信息不足',
  CONTACT: '建议沟通', SKIP: '不建议沟通', REVIEW: '需要进一步判断',
  FILTERED_OUT: '硬性排除',
  CONVERSATION_ACTIVE: '已有会话', GREETING_SENT_PENDING_SYNC: '已打招呼，等待消息同步',
  GREETING_RETRY_PENDING: '发送失败，等待重试', GREETING_OUTCOME_UNKNOWN: '发送结果待确认',
  GREETING_IN_PROGRESS: '正在发起沟通', GREETING_FAILED: '发送失败',
  GREETING_SENT: '已成功发送招呼', GREETING_NOT_SENT: '未能发送招呼',
  GREETING_PREWRITE_FAILED: '发送前检查失败',
  PREWRITE_GREETING_RETRY: '发送招呼失败，等待重试',
  READY_TO_CONTACT: '满足条件，尚未发起', NOT_CONTACTED: '未发起沟通',
  APPROVED_TARGET_PAGE_NOT_FOUND: '发送时没有找到对应职位页',
  APPROVED_TARGET_PAGE_AMBIGUOUS: '检测到多个相同职位页',
  SUPPORTED_PAGE_ROOT_NOT_FOUND: '职位页面结构发生变化',
  GREETING_ALREADY_EXISTS: '已有招呼动作', AUTO_GREET_DISABLED: '主动沟通开关未开启',
  STRATEGY_NOT_BOUND: '尚未绑定求职策略',
  JOB_ALREADY_HAS_CONVERSATION: '已有沟通会话，无需再次打招呼',
  JOB_ALREADY_CONTACTED: '该职位已经联系过',
  SAME_COMPANY_TITLE_ALREADY_CONTACTED: '同公司同名职位已联系过',
  SIMILAR_JD_ALREADY_CONTACTED: '高度相似的职位已联系过',
  COMPANY_COOLDOWN_ACTIVE: '同公司联系间隔尚未结束',
  RECRUITER_COOLDOWN_ACTIVE: '同招聘人联系间隔尚未结束',
  HEADHUNTER_PROACTIVE_CONTACT_BLOCKED: '猎头发布，按策略不主动打招呼',
  LLM_DOES_NOT_RECOMMEND_CONTACT: 'AI 判断暂不建议主动沟通',
  PROACTIVE_CONTACT_CANDIDATE: '满足主动沟通条件',
  PROACTIVE_CONTACT_NOT_ELIGIBLE: '未满足主动沟通条件',
  OUTSIDE_WORKING_HOURS: '当前不在自动沟通时间内',
  EMERGENCY_STOP_ACTIVE: '系统紧急停止中',
  PROHIBITED_OR_FRAUD_DIRECTION: '岗位疑似违规、欺诈或明确不接受',
  COMPANY_BLACKLISTED: '公司在黑名单中', INDUSTRY_EXCLUDED: '行业属于排除范围',
  WORK_MODE_CONFLICT: '工作模式不符合要求', LOCATION_CONFLICT: '工作地点不符合要求',
  WORK_MODE_UNKNOWN: '办公方式尚未明确',
  WORK_MODE_DISABLED: '求职策略未开启该工作模式',
  ONSITE_LOCATION_NOT_ALLOWED: '现场办公地点不在允许范围',
  HYBRID_LOCATION_NOT_ALLOWED: '混合办公地点不在允许范围',
  SALARY_CONFLICT: '薪资低于要求', SALARY_BELOW_CONTACT_THRESHOLD: '薪资低于沟通门槛',
  JOB_DIRECTION_CONFLICT: '岗位方向不符合求职方向',
  JOB_DIRECTION_UNKNOWN: '岗位方向信息不足',
  TITLE_EXCLUDED: '职位名称命中排除规则',
  TITLE_STRONGLY_IRRELEVANT: '职位名称与求职方向明显无关',
  REQUIRED_CORE_SKILL_MISSING: '缺少策略要求的核心技能',
  FULL_TIME_BACHELOR_REQUIRED: '职位明确要求全日制本科',
  OUTSOURCING_NOT_ACCEPTED: '策略不接受该外包岗位',
  PART_TIME_NOT_ACCEPTED: '策略不接受兼职岗位',
  HEADHUNTER_NOT_ACCEPTED: '策略不接受猎头岗位',
  INTERNSHIP_POSITION: '实习岗位不符合策略',
  JUNIOR_POSITION: '职级明显低于求职目标',
  JOB_NOT_OPEN: '职位已关闭或不可投递',
  RECRUITER_UNKNOWN: '无法确认招聘人身份',
  ANONYMOUS_COMPANY: '公司名称未公开',
  EXTERNAL_JOB_ID_MISSING: '未识别到平台职位编号',
  JOB_DETAIL_MISSING: '未能读取职位详情',
  JOB_DETAIL_NOT_READY: '职位详情尚未加载完成',
  JOB_DETAIL_OPEN_FAILED: '打开职位详情失败',
  JOB_RETRY_TARGET_NOT_VISIBLE: '重试时未找到目标职位',
  RETRY_ATTEMPTS_EXHAUSTED: '已达最大重试次数',
  HARD_FILTERED: '未通过硬性规则',
  JOB_SCAN_DISABLED_OR_PAUSED: '职位发现已关闭或暂停',
  NEXT_SCAN_NOT_DUE: '尚未到下次职位扫描时间',
  WAITING_FOR_LLM_RECOVERY: '等待 AI 服务恢复',
  LLM_NOT_CONFIGURED: 'AI 服务未配置',
  LLM_AUTHENTICATION_FAILED: 'AI 服务认证失败',
  LLM_RATE_LIMITED: 'AI 服务请求受限',
  LLM_TIMEOUT: 'AI 服务响应超时',
  LLM_NETWORK_ERROR: 'AI 服务网络异常',
  LLM_SERVICE_ERROR: 'AI 服务返回异常',
  FULL_JOB_CONTEXT_AVAILABLE: '岗位信息充分且符合策略',
  RELATED_DIRECTION_WITHOUT_CONFLICT: '岗位方向相关，暂未发现明确冲突',
  RESUME_SEND_DENIED: '简历发送条件未满足',
  INBOUND_RESUME_REQUEST_ALLOWED: '对方索要简历，可以自动发送',
  QUALIFICATION_MISMATCH: '岗位已判定不匹配',
  ALLOW_AUTO: '允许自动执行', REQUIRE_CONFIRMATION: '等待人工确认', DENY: '不会执行',
  RULE_TEMPLATE: '规则回复', KNOWLEDGE_BASE: '知识库回复', LLM: 'AI生成', HUMAN: '人工处理',
  PENDING: '等待执行', ACTIVE: '处理中', FAILED: '发送失败', DENIED: '不会发送',
}

export const businessLabel = (code?: string) => {
  if (!code) return '-'
  return labels[code] ?? `未知状态（${code}）`
}
